#' Ingest BP data to prepare for iCe
#'
#' This function reads in a dataset of points (relative time x relative blood pressure) extracted from a pdf (generated by EndoPat by Itamar)
#'
#' @param x csv file with two columns: relative time and relative BP
#'
#' @return data2 -- data table for use in calcLocalMax
#' @export read_data
#'
#' @import dplyr
#'
#' @examples read_data("data.csv")
read_data <- function(x) {

  wd <- getwd()
  data <- read.csv(paste0(wd, "/", x), header=FALSE)

  setnames(data, 'V1', 'Relative_time')
  setnames(data, 'V2', 'Pressure')

  #class(data$Pressure)

  data2 <<- as.data.table(data)

  plot(data2)
}

#' Calculate the Local Maxima of a Dataset
#'
#' This function serves to calculate all the local maxima of a dataset or, if the data is first multiplied by -1 in the input, the local minima
#'
#' @param x the dataset contaiing the dependent variable of the data set for which you want the maxima
#'
#' @return y -- vector of row numbers which describe local maxima
#' @export localMaxima
#'
#' @examples Output <- localMaxima(datatable$dependentvariable)
localMaxima <- function(x) {
  # Use -Inf if x is numeric
  y <- diff(c(-.Machine$integer.max, x)) > 0L #get max negative integer and add as value 1, then calculate diff between each column, then create boolean if value is positive/negative
  rle(y)$lengths #included just for debug to ensure the run-length encoding runs ok even though repeated below
  y <- cumsum(rle(y)$lengths) #rle to get run-length encoding to count number of values between maxima and cumsum to add space between maxima to get row numbers where maxima are found
  y <- y[seq.int(1L, length(y), 2L)] #rle has all the "1" next to count so take every other number to remove these
  if (x[[1]] == x[[2]]) {
    y <- y[-1]
  }
  y #drop first row remaining from appending max integer
}

#' Execute the localMaxima Function
#'
#' This function uses the localMaxima function to assess the data table created by read_data
#'
#' @param x Datatable of relative time x relative pressure
#'
#' @return MaximaRows -- Dataset of selected local maxima in ingested datatable
#' @export calcLocalMax
#'
#' @examples calcLocalMax(data2)
calcLocalMax <- function(x) {
  x <- x[order(Relative_time)]
  LocalMaxima <- localMaxima(x$Pressure)
  x$link <- seq.int(nrow(x))
  MaximaRows <<- x[x$link %in% LocalMaxima, ]

  plot(y = MaximaRows$Pressure, x = MaximaRows$Relative_time)
}

#' Execute the localMaxima Function to find minima
#'
#' This function uses the localMaxima function to assess the ingested data table but first manipulates data (mulitply by -1) to instead find minima
#'
#' @param x Datatable of relative time x relative pressure
#'
#' @return MaximaRows -- Dataset of local minima in ingested dataset
#' @export calcLocalMin
#'
#' @examples calcLocalMin(data2)
calcLocalMin <- function(x) {
  data4 <- x
  x <- x[order(Relative_time)]
  x$row_num <- seq.int(nrow(x))
  data4$Pressure <- x$Pressure*-1
  LocalMinima <- localMaxima(data4$Pressure)
  MinimaRows <<- x[x$row_num %in% LocalMinima, ]

  plot(y = MinimaRows$Pressure, x = MinimaRows$Relative_time)
}

#' Clean MaximaRows output to isolate valid systolic BP
#'
#' local maxima for a pressure wave will find systolic BP but also a point into a dichroic notch which this function will aim to remove
#' Note that this local value removal code serves limited function now with the new data extraction method but was left in to prevent any potential extraneous values

#'
#' @param x Dataset of local maxima in ingested dataset
#'
#' @return FinalMaxima3 -- Dataset of cleaned local maxima (nearly completely diastolic BP) in ingested dataset
#' @export localvalremoveMax
#'
#'
#' @examples localvalremoveMax(MaximaRows)
localvalremoveMax <- function(x) {
  ###Dropped Code###
  #setorder(x, cols = -"Pressure")
  #x$Relative_time<- round_any(x$Relative_time, accuracy = 2, f = ceiling)
  #setorder(x, cols = -"Pressure")
  #FinalMaxima <- distinct(x, Relative_time, .keep_all=TRUE)

  setorder(x, cols = "Relative_time")
  FinalMaxima2 <- mutate(x, difcheck = Pressure + -lag(Pressure)) #calculate a new column to find difference in pressure between adjacent two points (to reveal where pressure jump is high and, thus, likely part of dichroic notch)
  FinalMaxima2[is.na(FinalMaxima2)] <- 0 #recode NA to 0
  FinalMaxima3 <- FinalMaxima2[FinalMaxima2$difcheck >= -100 & FinalMaxima2$difcheck <= 100, ] #select only columns where change in pressure isn't >100

  FinalMaxima31 <- mutate(FinalMaxima3, difcheck = Pressure + -lag(Pressure)) #cycling to remove clusters of aberrant data
  FinalMaxima31[is.na(FinalMaxima31)] <- 0
  FinalMaxima32 <- FinalMaxima31[FinalMaxima31$difcheck <= 100 & FinalMaxima31$difcheck >= -100, ]

  FinalMaxima33 <- mutate(FinalMaxima32, difcheck = Pressure + -lag(Pressure))
  FinalMaxima33[is.na(FinalMaxima33)] <- 0
  FinalMaxima4 <<- FinalMaxima33[FinalMaxima33$difcheck <= 100 & FinalMaxima33$difcheck >= -100, ]

  plot(y = FinalMaxima4$Pressure, x = FinalMaxima4$Relative_time)
  }

#' Clean Minima output to isolate valid diastolic BP
#'
#' local maxima (w/ -1 manipulation) for a pressure wave will find diastolic BP but also a point into a dichroic notch which this function will aim to remove
#' Note that this local value removal code serves limited function now with the new data extraction method but was left in to prevent any potential extraneous values
#'
#' @param x Dataset of local maxima in ingested dataset
#'
#' @return FinalMaxima3 -- Dataset of cleaned local maxima in ingested dataset
#' @export localvalremoveMin
#'
#' @examples localvalremoveMin(MinimaRows)
localvalremoveMin <- function(x) {
  ###Dropped Code###
  #x$Relative_time<- round_any(x$Relative_time, 2, f = ceiling)
  #setorder(x, cols = "Pressure")

  #FinalMinima <- distinct(x, Relative_time, .keep_all=TRUE)

  setorder(x, cols = "Relative_time")  #reset order based on relative time
  FinalMinima2 <- mutate(x, difcheck = Pressure + -lag(Pressure)) #calc a new column to find difference in pressure between adjacent two points (to reveal where pressure jump is high and, thus, likely part of dichroic notch)
  FinalMinima2[is.na(FinalMinima2)] <- 0
  FinalMinima3 <- FinalMinima2[FinalMinima2$difcheck <= 100 & FinalMinima2$difcheck >= -100, ]

  FinalMinima31 <- mutate(FinalMinima3, difcheck = Pressure + -lag(Pressure)) #cycling to remove clusters of abberant data
  FinalMinima31[is.na(FinalMinima31)] <- 0
  FinalMinima32 <- FinalMinima31[FinalMinima31$difcheck <= 100 & FinalMinima31$difcheck >= -100, ]

  FinalMinima33 <- mutate(FinalMinima32, difcheck = Pressure + -lag(Pressure))
  FinalMinima33[is.na(FinalMinima33)] <- 0
  FinalMinima4 <<- FinalMinima33[FinalMinima33$difcheck <= 100 & FinalMinima33$difcheck >= -100, ]

  plot(y = FinalMinima4$Pressure, x = FinalMinima4$Relative_time)
}

#' Calculate Pulse wave and Fit non-parametric curve
#'
#' This function calculates a non-parametric curve (spline) for the systolic and then diastolic BP data tables, predicts a set of values for each, and uses the predicted values to calculate a pulse pressure for which it then outputs a nonparametric curve
#'
#' @param x data table of systolic maxima
#' @param y data table of diastolic minima
#' @param n string used to name the output png
#'
#' @return predpulsewave -- data table of predicted pulse pressure values
#' @export nonparam
#'
#' @examples nonparam(FinalMaxima4, FinalMinima4, name)
nonparam <- function(x, y, n) {
  a <- min(x$Relative_time)
  b <- max(x$Relative_time)

  spline <- smooth.spline(x = y$Relative_time, y = y$Pressure, df = 4)
  newx <- seq(a, b, by = 1)
  newvals <- predict(spline, x = newx)
  newvals <- as.data.table(newvals)
  setnames(newvals, 'x', 'Relative_time')
  setnames(newvals, 'y', 'Diastolic_Minima')

  spline <- smooth.spline(x = x$Relative_time, y = x$Pressure, df = 6)
  newx <- seq(a, b, by = 1)
  newvals2 <<- predict(spline, x = newx)
  newvals2 <<- as.data.table(newvals2)
  setnames(newvals2, 'x', 'Relative_time')
  setnames(newvals2, 'y', 'Systolic_Maxima')

  newvals2$Diastolic_Minima <<- newvals$Diastolic_Minima
  newvals2$Pulse_Wave <<- newvals2$Systolic_Maxima - newvals2$Diastolic_Minima

  predpulsewave <<- newvals2

  #name <- paste0("PulseWave_", n, ".png")
  #png(file=name, height = 500, width = 600, point=16)
  #plot(newvals2$Pulse_Wave ~ newvals2$Relative_time, type = 'l', xlab = "Relative Time", ylab = "Pulse Wave")
  #dev.off()
}


#' New ggplot curve to highlight key data features
#'
#' This function uses ggplot to plot a pulse pressure graph which has in red the two inflection points and in blue the portion of the graph used to calculate the initial slope
#'
#' @param x data table of predicted pulse pressures from the graphing function non-parametric curve
#' @param n string used to name the output png
#'
#' @return NewPulseWave_n.csv
#' @export iCegraph
#'
#' @import ggplot2
#'
#' @examples iCegraph(predpulsewave, name)
#'
iCegraph <- function(x, n) {
  wd <- getwd()
  forgg <- as.data.table(x)

  inflectionpts <- as.list(inflection_points$Relative_time)

  forgg$min[forgg$Relative_time %in% inflectionpts] <- "1"
  forgg$min[!(forgg$Relative_time %in% inflectionpts)] <- "0"
  forgg$intslope[forgg$Relative_time <50] <- "1"
  forgg$intslope[forgg$Relative_time >50] <- "0"
  forgg$intslope[forgg$Relative_time == 50] <- "0"

  assign(paste(m, sep='_'), forgg, envir = globalenv())

  #name2 <- paste0("NewPulseWave_", n, ".png")
  #ggplot(forgg, aes(x = Relative_time, y = Pulse_Wave) ) +
    #geom_point() +
    #geom_point(data=forgg[forgg$min == "1",],color="red",size=3) +
    #geom_point(data=forgg[forgg$intslope == "1",],color="blue") +
    #xlim(0, 250) +
    #ylim(0, 360) +
    #theme_classic() +
    #xlab("Relative Time")+
    #ylab("Relative Pressure")+
    #theme(
      #axis.title.x = element_text(size = 16),
      #axis.text.x = element_text(size = 14),
      #axis.title.y = element_text(size = 16),
      #axis.text.y = element_text(size = 14),
      #legend.position="none")

  #ggsave(
    #name2,
    #plot = last_plot(),
    #path = wd,
    #scale = 1
  #)
}

#' Calculate first derivative of the pulse wave
#'
#' @param x data table of predicted pulse pressure values
#' @param n string used to name the output png
#'
#' @return dapulsewave -- data table of predicted pulse pressure values with the addition of first derivative (da) values
#' @return FirstDev_n.png
#'
#' @import Hmisc
#'
#' @examples firstdev(predpulsewave, name)
firstdev <- function(x, n) {
  x <- mutate(x, da = Pulse_Wave + -Lag(Pulse_Wave, shift = 1))
  x[is.na(x)] <- 0
  x <- x[-c (1), ]
  dapulsewave <<- x
  name <- paste0("FirstDev_", n, ".png")
  png(file=name, height = 500, width = 600, point=16)
  plot(x$da ~ x$Relative_time, type = 'l', xlab = "Relative Time", ylab = "First Derivative Pulse Wave", xlim=c(0, 250), ylim=c(-1.5, 4))
  dev.off()
}

#' Calculate slope of linear phase of pulse wave
#'
#' This is used to find a linear regression of the first portion of the graph to be output for use in iCe
#'
#' @param x data table of predicted pulse pressure values
#' @param n string used to name the outputs
#'
#' @return InitialSlope_n.png
#' @export initialslope
#'
#' @examples initialslope(predpulsewave, name)
initialslope <- function(x, n) {
  #localmax <- localMaxima(x$Pulse_Wave)
  #x$row_num <- seq.int(nrow(x))
  #find <- x[x$row_num %in% localmax, ]
  #setorder(find, cols = "Relative_time")
  #max <- find$Relative_time[1]
  IntSlope <- x[x$Relative_time < 50, ]
  #name <- paste0("InitialSlope_", n, ".png")
  #png(file=name, height = 500, width = 600, point=16)
  #plot(IntSlope$Pulse_Wave ~ IntSlope$Relative_time, type = 'l', xlab = "Relative Time", ylab = "Initial Pulse Wave")
  #dev.off()
  model <- lm(Pulse_Wave ~ Relative_time, data = IntSlope)
  name <- paste0(n, "_linearregression")
  sink(name)
  print(summary(model))
  sink()
}

#' Find minimum points of first derivative
#'
#' Finds the inflection points of the pulse pressure graph to be used in iCe
#'
#' @param x data table of predicted pulse pressure values which includes first derivatives
#'
#' @return inflection_points -- two lowest amplitude minima of the first derivative graph
#' @export inflecpoints
#'
#' @examples inflecpoints(dapulsewave)
inflecpoints <- function(x) {
  a <- min(x$Relative_time)
  b <- max(x$Relative_time)

  x$da <- x$da*-1
  dalocalmin <- localMaxima(x$da)
  x$row_num <- seq.int(nrow(x))
  daminima <- x[x$row_num %in% dalocalmin, ]
  setorder(daminima, cols = "da")
  inflection_point <- tail(daminima, n=2)

  localmax <- localMaxima(x$Pulse_Wave)
  lmax <- x[x$row_num %in% localmax, ]
  setorder(lmax, cols = "Pulse_Wave")
  max <- head(lmax, n=1)

  x$Pulse_Wave <- x$Pulse_Wave*-1
  localmin <- localMaxima(x$Pulse_Wave)
  lmin <- x[x$row_num %in% localmin, ]
  setorder(lmin, cols = "Pulse_Wave")
  min <- tail(lmin, n=1)

  inflection_points <- rbind(inflection_point,max,min)
  inflection_points <<- filter(inflection_points, Relative_time != a & Relative_time != b)
}

#' Make a ggplot overlay for client viewing
#'
#' @param x pre-exercise data
#' @param y post-exercise data
#' @param n string for naming
#' @param l string for Pressure minima
#' @param o string for Pressure maxima
#' @param v string for Time minima
#' @param z string for Time maxima
#'
#' @return ClientGraph_test.png
#' @export Clientgraph
#'
#' @import png
#' @import grid
#' @import ggpubr
#'
#' @examples Clientgraph(Pre, Post, "name", "0", "600", "0", "300")
Clientgraph <- function(x, y, n, l, o, v, z) {
  min <- as.numeric(l)
  max <- as.numeric(o)
  tmin <- as.numeric(v)
  tmax <- as.numeric(z)

  wd <- getwd()
  name2 <- paste0("ClientGraph_", n, ".png")
  x$Time <- x$Relative_time/2.16 #multiplier is to turn relative units to seconds calculated from a reference screenshot
  y$Time <- y$Relative_time/2.16

  img <- readPNG("iCe_vector.png")
  g2 <- matrix(rgb(img[,,1],img[,,2],img[,,3],img[,,4] * 0.15), nrow=dim(img)[1]) ## you can change 0.5 to change the alpa
  g <- rasterGrob(g2, interpolate=TRUE)
  #ref <- readPNG("refGraph.png")
  #ref2 <- rasterGrob(ref, interpolate=TRUE)

  ggplot(x, aes(x = Time, y = Pulse_Wave) ) +
    annotation_custom(g, xmin=(tmax-.95*tmax), xmax=(0.95*tmax), ymin=(max-0.95*max), ymax=(0.95*max)) +
    #annotation_custom(ref2, xmin=210, xmax=Inf, ymin=-Inf, ymax=100)+
    geom_point(color= "#197E9A") +
    geom_point(data=x[x$min == "1",],color="#002f65",size=3) +
    geom_point(data=x[x$intslope == "1",],color="#2dbfc6") +
    geom_point(data = y, color="#cd2400") +
    geom_point(data=y[y$min == "1",],color="#8b0000",size=3) +
    geom_point(data=y[y$intslope == "1",],color="#FF4F00") +
    #geom_hline(yintercept=c(125, 200), linetype='dashed', color=c('red', 'red')) +
    xlim(tmin, tmax) +
    ylim(min, max) +
    theme_classic() +
    xlab("Time (seconds)")+
    ylab("Pulse Pressure")+
    theme(
      axis.title.x = element_text(size = 16, face="bold"),
      axis.text.x = element_text(size = 14),
      axis.title.y = element_text(size = 16, face="bold"),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      #plot.background = element_rect(fill = "transparent", color = NA),
      #panel.background = element_rect(fill = "transparent"),
      legend.position="none")

  ggsave(
    name2,
    plot = last_plot(),
    path = wd,
    scale = 1,
    width = 6.03,
    height = 7.04
    #bg = "transparent"
  )
}
